spring.kafka.bootstrap-servers=broker:9092

spring.kafka.consumer.group-id=notification-service

spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/