spring.application.name=notification-service

spring.cloud.config.enabled=true

spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false